---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    app: hello-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
      - name: node
        image: docker.io/bmngld/hello-service:v0.0.1
        ports:
        - containerPort: 3000
          protocol: TCP
